export const englishQaRoutes = [
  "/",
  "/about",
  "/research",
  "/projects",
  "/projects/gnaroshi-dev/",
  "/projects/gnaroshi-vla/",
  "/projects/gnaroshi-studio/",
  "/projects/paperflow/",
  "/projects/arxiv-discovery/",
  "/projects/runshelf/",
  "/projects/tr-gpu-monitor/",
  "/projects/contentdeck/",
  "/blog",
  "/blog/archive/",
  "/papers",
  "/growth",
  "/queue",
  "/reviews",
  "/reviews/due/",
  "/formula",
  "/questions",
  "/implementations",
  "/graph",
  "/week",
  "/now",
  "/contact",
  "/404"
] as const;

export const koreanQaRoutes = [
  "/ko/",
  "/ko/about",
  "/ko/research",
  "/ko/projects",
  "/ko/projects/gnaroshi-dev/",
  "/ko/projects/gnaroshi-vla/",
  "/ko/projects/gnaroshi-studio/",
  "/ko/projects/paperflow/",
  "/ko/projects/arxiv-discovery/",
  "/ko/projects/runshelf/",
  "/ko/projects/tr-gpu-monitor/",
  "/ko/projects/contentdeck/",
  "/ko/blog",
  "/ko/blog/archive/",
  "/ko/papers",
  "/ko/growth",
  "/ko/queue",
  "/ko/reviews",
  "/ko/reviews/due/",
  "/ko/formula",
  "/ko/questions",
  "/ko/implementations",
  "/ko/graph",
  "/ko/week",
  "/ko/now",
  "/ko/contact",
  "/ko/404"
] as const;

export const qaRoutes = [...englishQaRoutes, ...koreanQaRoutes] as const;

export const qaViewports = [
  { name: "desktop", width: 1440, height: 900 },
  { name: "tablet", width: 1024, height: 768 },
  { name: "tablet-768", width: 768, height: 1024 },
  { name: "mobile-430", width: 430, height: 932 },
  { name: "mobile-390", width: 390, height: 844 },
  { name: "mobile-360", width: 360, height: 800 },
  { name: "mobile-320", width: 320, height: 568 }
] as const;
